apiVersion: v1
kind: Service
metadata:
  name: health-service
  namespace: ssid-zero_time_auth
spec:
  selector:
    app: health
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
