apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: ssid-foundation
spec:
  selector:
    app: communication
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
