apiVersion: apps/v1
kind: Deployment
metadata:
  name: contracts-service
  namespace: ssid-interoperability
  labels:
    app: contracts
    root: interoperability
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contracts
  template:
    metadata:
      labels:
        app: contracts
        root: interoperability
    spec:
      containers:
      - name: contracts
        image: registry.ssid.local/ssid/interoperability-contracts:2.0.0
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: contracts-secrets
              key: redis-url
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: contracts-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
