# SSID Policy Compliance Tests - Consolidated
# Auto-generated by policy_compiler.py
# Generated: 2025-10-11T18:48:56.708621Z

package ssid.compliance_test

import data.ssid.compliance

# Test all policies are compliant with valid input
test_all_compliant {
    compliance.all_compliant with input as {
        "governance_enabled": true,
        "audit_trail_enabled": true,
        "data_protection_enabled": true,
        "encryption_enabled": true,
        "access_control_enabled": true,
        "transparency_enabled": true,
        "incident_response_enabled": true,
        "testing_enabled": true,
        "third_party_monitoring_enabled": true,
        "compliance_framework_enabled": true
    }
}

# Test violations are detected with invalid input
test_violations_detected {
    count(compliance.violations) > 0 with input as {
        "governance_enabled": false
    }
}
