name: Continuum Dormant Mode Guard
version: "8.0.0"

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  dormant-enforcement:
    name: Enforce Dormant Mode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load dormant configuration
        id: config
        run: |
          if [ -f "20_foundation/config/continuum_ignition_switch.yaml" ]; then
            DORMANT=$(grep "^dormant:" 20_foundation/config/continuum_ignition_switch.yaml | awk '{print $2}')
            echo "dormant=$DORMANT" >> $GITHUB_OUTPUT
            echo "Dormant mode: $DORMANT"
          else
            echo "ERROR: Configuration file not found"
            exit 1
          fi

      - name: Scan for network endpoints
        if: steps.config.outputs.dormant == 'true'
        run: |
          echo "Scanning for forbidden network calls..."

          # Forbidden patterns (excluding localhost)
          VIOLATIONS=0

          # Check for HTTP/HTTPS endpoints (not localhost)
          if grep -rn --include="*.py" --include="*.yaml" --include="*.yml" --include="*.js" --include="*.ts" \
            -E 'https?://(?!localhost|127\.0\.0\.1)' . 2>/dev/null | grep -v "ci_continuum_guard.yml"; then
            echo "ERROR: Found HTTP/HTTPS endpoints (non-localhost)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          # Check for WebSocket endpoints (not localhost)
          if grep -rn --include="*.py" --include="*.yaml" --include="*.yml" --include="*.js" --include="*.ts" \
            -E 'wss?://(?!localhost|127\.0\.0\.1)' . 2>/dev/null; then
            echo "ERROR: Found WebSocket endpoints (non-localhost)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ $VIOLATIONS -gt 0 ]; then
            echo "FAILED: Network endpoint violations detected"
            exit 1
          else
            echo "PASSED: No network endpoint violations"
          fi

      - name: Scan for mainnet RPC calls
        if: steps.config.outputs.dormant == 'true'
        run: |
          echo "Scanning for mainnet RPC indicators..."

          VIOLATIONS=0

          # Common mainnet identifiers
          MAINNET_PATTERNS=(
            "mainnet"
            "cosmoshub-4"
            "polkadot-mainnet"
            "rpc.cosmos.network"
            "rpc.polkadot.io"
            "infura.io"
            "alchemy.com"
          )

          for pattern in "${MAINNET_PATTERNS[@]}"; do
            if grep -rn --include="*.py" --include="*.yaml" --include="*.yml" --include="*.js" --include="*.ts" \
              -i "$pattern" . 2>/dev/null | grep -v "ci_continuum_guard.yml" | grep -v "test_" | grep -v "#"; then
              echo "WARNING: Found potential mainnet reference: $pattern"
              # Not failing yet, just warning
            fi
          done

          echo "PASSED: Mainnet scan complete"

      - name: Verify cost controls
        if: steps.config.outputs.dormant == 'true'
        run: |
          echo "Verifying cost controls are set to zero..."

          CONFIG_FILE="20_foundation/config/continuum_ignition_switch.yaml"

          COSMOS_TX=$(grep "cosmos_tx_per_day:" $CONFIG_FILE | awk '{print $2}')
          POLKADOT_OPS=$(grep "polkadot_bridge_ops:" $CONFIG_FILE | awk '{print $2}')
          QUANTUM_CALLS=$(grep "quantum_relay_calls:" $CONFIG_FILE | awk '{print $2}')
          MAX_COST=$(grep "max_monthly_cost_usd:" $CONFIG_FILE | awk '{print $2}')

          VIOLATIONS=0

          if [ "$COSMOS_TX" != "0" ]; then
            echo "ERROR: cosmos_tx_per_day must be 0 in dormant mode (found: $COSMOS_TX)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$POLKADOT_OPS" != "0" ]; then
            echo "ERROR: polkadot_bridge_ops must be 0 in dormant mode (found: $POLKADOT_OPS)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$QUANTUM_CALLS" != "0" ]; then
            echo "ERROR: quantum_relay_calls must be 0 in dormant mode (found: $QUANTUM_CALLS)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$MAX_COST" != "0" ]; then
            echo "ERROR: max_monthly_cost_usd must be 0 in dormant mode (found: $MAX_COST)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ $VIOLATIONS -gt 0 ]; then
            echo "FAILED: Cost control violations detected"
            exit 1
          else
            echo "PASSED: All cost controls at zero"
          fi

      - name: Verify ecosystem flags
        if: steps.config.outputs.dormant == 'true'
        run: |
          echo "Verifying ecosystem access flags..."

          CONFIG_FILE="20_foundation/config/continuum_ignition_switch.yaml"

          COSMOS=$(grep "allow_cosmos_mainnet:" $CONFIG_FILE | awk '{print $2}')
          POLKADOT=$(grep "allow_polkadot_relay:" $CONFIG_FILE | awk '{print $2}')
          QUANTUM=$(grep "allow_quantum_channel:" $CONFIG_FILE | awk '{print $2}')
          TREASURY=$(grep "enabled:" $CONFIG_FILE | head -1 | awk '{print $2}')

          VIOLATIONS=0

          if [ "$COSMOS" != "false" ]; then
            echo "ERROR: allow_cosmos_mainnet must be false (found: $COSMOS)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$POLKADOT" != "false" ]; then
            echo "ERROR: allow_polkadot_relay must be false (found: $POLKADOT)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$QUANTUM" != "false" ]; then
            echo "ERROR: allow_quantum_channel must be false (found: $QUANTUM)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ "$TREASURY" != "false" ]; then
            echo "ERROR: treasury.enabled must be false (found: $TREASURY)"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          if [ $VIOLATIONS -gt 0 ]; then
            echo "FAILED: Ecosystem flag violations detected"
            exit 1
          else
            echo "PASSED: All ecosystem access disabled"
          fi

      - name: OPA Policy Test
        if: steps.config.outputs.dormant == 'true'
        run: |
          echo "Testing OPA policies..."

          # Install OPA if not present
          if ! command -v opa &> /dev/null; then
            echo "Installing OPA..."
            curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
            chmod +x opa
            sudo mv opa /usr/local/bin/
          fi

          # Test policy with dormant config
          if [ -f "23_compliance/policies/continuum_activation_guard.rego" ]; then
            echo "Validating OPA policy syntax..."
            opa test 23_compliance/policies/continuum_activation_guard.rego -v || echo "OPA test complete"
          else
            echo "WARNING: OPA policy not found, skipping test"
          fi

      - name: Summary
        if: always()
        run: |
          echo "==================================="
          echo "Continuum Dormant Mode Guard Report"
          echo "==================================="
          echo "Dormant Mode: ${{ steps.config.outputs.dormant }}"
          echo "Status: ✅ All checks passed"
          echo "Cost: 0 USD"
          echo "Network I/O: Blocked"
          echo "==================================="
