apiVersion: v1
kind: Service
metadata:
  name: education-service
  namespace: ssid-tooling
spec:
  selector:
    app: education
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
