apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-service
  namespace: ssid-identity_score
  labels:
    app: access
    root: identity_score
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: access
  template:
    metadata:
      labels:
        app: access
        root: identity_score
    spec:
      containers:
      - name: access
        image: registry.ssid.local/ssid/identity_score-access:2.0.0
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: access-secrets
              key: redis-url
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: access-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
