apiVersion: v2
name: communication-service
description: SSID communication service Helm chart
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - ssid
  - zero_time_auth
  - communication
maintainers:
  - name: SSID Team
    email: team-14-04@example.local
