allowed_roots:
  - 01_ai_layer
  - 02_audit_logging
  - 03_core
  - 04_deployment
  - 05_documentation
  - 06_data_pipeline
  - 07_governance_legal
  - 08_identity_score
  - 09_meta_identity
  - 10_interoperability
  - 11_test_simulation
  - 12_tooling
  - 13_ui_layer
  - 14_zero_time_auth
  - 15_infra
  - 16_codex
  - 17_observability
  - 18_data_layer
  - 19_adapters
  - 20_foundation
  - 21_post_quantum_crypto
  - 22_datasets
  - 23_compliance
  - 24_meta_orchestration
  - .github
  - .git
  - .gitattributes
  - .gitmodules
  - .LICENSE
  - .README
  - .claude
  - ssid_validator
  - .pytest
