apiVersion: v1
kind: Service
metadata:
  name: employment-service
  namespace: ssid-test_simulation
spec:
  selector:
    app: employment
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
