apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobility-service
  namespace: ssid-meta_identity
  labels:
    app: mobility
    root: meta_identity
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobility
  template:
    metadata:
      labels:
        app: mobility
        root: meta_identity
    spec:
      containers:
      - name: mobility
        image: registry.ssid.local/ssid/meta_identity-mobility:2.0.0
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mobility-secrets
              key: redis-url
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: mobility-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
