apiVersion: v1
kind: Service
metadata:
  name: commerce-service
  namespace: ssid-infra
spec:
  selector:
    app: commerce
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
