apiVersion: v2
name: government-service
description: SSID government service Helm chart
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - ssid
  - documentation
  - government
maintainers:
  - name: SSID Team
    email: team-05-16@example.local
