apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: ssid-ui_layer
  labels:
    app: communication
    root: ui_layer
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
        root: ui_layer
    spec:
      containers:
      - name: communication
        image: registry.ssid.local/ssid/ui_layer-communication:2.0.0
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: communication-secrets
              key: redis-url
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: communication-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
