apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  namespace: ssid-codex
spec:
  selector:
    app: insurance
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
