apiVersion: deployment.ssid.project/v1
kind: ShardManifest
metadata:
  name: 23_compliance_09_arbeit_karriere
  labels:
    root: 23_compliance
    shard: 09_arbeit_karriere
    domain: work_finance
spec:
  replicas: 1
  deployment:
    strategy: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
