apiVersion: v1
kind: Service
metadata:
  name: business-service
  namespace: ssid-adapters
spec:
  selector:
    app: business
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
