apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: ssid-data_pipeline
spec:
  selector:
    app: finance
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
