apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-service
  namespace: ssid-governance_legal
  labels:
    app: documents
    root: governance_legal
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
        root: governance_legal
    spec:
      containers:
      - name: documents
        image: registry.ssid.local/ssid/governance_legal-documents:2.0.0
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: documents-secrets
              key: redis-url
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: documents-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
