apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: ssid-documentation
spec:
  selector:
    app: identity
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
