apiVersion: v1
kind: Service
metadata:
  name: contracts-service
  namespace: ssid-governance_legal
spec:
  selector:
    app: contracts
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
