# SSID Pre-Commit Configuration (PROMPT 6)
# Enforces canonical score references

repos:
  - repo: local
    hooks:
      - id: no-raw-scores
        name: No Raw Scores Lint
        entry: python 12_tooling/hooks/lints/no_raw_scores.py
        language: system
        types: [text]
        files: \.(md|yaml|yml|json|txt)$
        exclude: '\.score\.json$'
        always_run: false
        pass_filenames: true
        description: Blocks commits containing raw X/100 or X/400 scores without SCORE_REF

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: '\.score\.json$'
