# 12_tooling/ci/layer_v5_foundation_check.yml
name: Layer v5 Foundation Check (thr=0.90)
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  audit-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pytest
      - name: Readiness Audit (L1–L8, thr=0.90)
        run: |
          python 11_test_simulation/layer_readiness_audit.py --project-root "${{ github.workspace }}"
      - name: Run Tests
        run: |
          pytest -q 11_test_simulation/tests
