version: "1.0.0"
name: "SSID Performance Cache Configuration"
compliance: "SHOULD-002-CACHE-LAYER"
generated: "2025-10-10T13:15:00Z"

cache_tiers:
  l1_memory:
    enabled: true
    max_size: 1000
    eviction_policy: "lru"
    default_ttl_seconds: 3600
    max_entry_size_bytes: 1048576  # 1MB
    monitoring:
      hit_rate_alert_threshold_percent: 50
      eviction_rate_alert_threshold_per_hour: 100

  l2_redis:
    enabled: false  # Requires Redis infrastructure
    host: "localhost"
    port: 6379
    db: 0
    password: ""
    max_connections: 50
    socket_timeout_seconds: 2
    default_ttl_seconds: 7200
    max_memory_mb: 512
    eviction_policy: "allkeys-lru"
    monitoring:
      hit_rate_alert_threshold_percent: 60
      latency_alert_threshold_ms: 10

  l3_database:
    enabled: false  # Requires DB cache table
    table_name: "cache_entries"
    max_entries: 100000
    cleanup_interval_seconds: 3600
    default_ttl_seconds: 86400  # 24 hours

cache_policies:
  anti_gaming:
    key_prefix: "anti_gaming"
    ttl_seconds: 300  # 5 minutes
    tier: "l1_memory"
    description: "Cache for anti-gaming proof reuse checks"

  identity_score:
    key_prefix: "identity_score"
    ttl_seconds: 600  # 10 minutes
    tier: "l1_memory"
    description: "Cache for identity score calculations"

  badge_verification:
    key_prefix: "badge_verify"
    ttl_seconds: 180  # 3 minutes
    tier: "l1_memory"
    description: "Cache for badge signature verifications"

  health_checks:
    key_prefix: "health"
    ttl_seconds: 30  # 30 seconds
    tier: "l1_memory"
    description: "Cache for health check dependency status"

monitoring:
  prometheus_metrics: true
  metrics_endpoint: "/metrics"
  audit_logging: true
  cache_event_types:
    - "cache_hit"
    - "cache_miss"
    - "cache_set"
    - "cache_eviction"
    - "cache_invalidation"
    - "cache_clear"

compliance:
  regulatory_requirements:
    - "DORA Art.9 (Protection and Prevention) - Performance optimization"
    - "ISO 27001:2022 A.12.1.3 - Capacity management"
  audit_retention_days: 30
  cache_statistics_retention_days: 90

performance_targets:
  l1_hit_rate_percent: 80
  l1_average_latency_microseconds: 100
  l2_hit_rate_percent: 90
  l2_average_latency_ms: 5
  cache_memory_overhead_mb: 100

signoff:
  config_version: "1.0.0"
  approved_by: "SSID Performance Team"
  approval_date: "2025-10-10"
  next_review: "2026-01-10"
