apiVersion: deployment.ssid.project/v1
kind: ShardManifest
metadata:
  name: 09_meta_identity_01_identitaet_personen
  labels:
    root: 09_meta_identity
    shard: 01_identitaet_personen
    domain: identity_foundation
spec:
  replicas: 1
  deployment:
    strategy: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
