apiVersion: ssid/root/v1
kind: RootChart
metadata:
  name: deployment
  version: "0.1.0"
  description: "Deployment configurations, infrastructure as code, and environment management"
  created: "2025-10-13"
  status: bootstrap

spec:
  capabilities:
    - infrastructure_as_code
    - multi_environment_deployment
    - blue_green_deployments
    - canary_releases
    - rollback_automation
    - configuration_management

  interfaces:
    - name: deployment_api
      type: rest_api
      authentication: required
      authorization: rbac

    - name: infrastructure_provisioning
      type: terraform
      authentication: required

    - name: config_management
      type: gitops
      authentication: required

  policies:
    - name: environment_isolation
      enforcement: automated
      scope: all_environments

    - name: secret_management
      enforcement: automated
      scope: all_deployments
      mechanism: vault

    - name: deployment_approval
      enforcement: manual
      scope: production
      approvers: 2

  dependencies:
    internal:
      - 15_infra  # Infrastructure layer
      - 23_compliance  # Compliance validation
      - 02_audit_logging  # Deployment logging
    external:
      - terraform: ">=1.5"
      - kubernetes: ">=1.27"
      - helm: ">=3.12"

  governance:
    maintainer: "DevOps Team"
    reviewers:
      - sre_team
      - security_team
    approval_required: true
    data_classification: confidential

  compliance:
    dora:
      - article_9  # Protection and prevention
      - article_21  # Resilience testing
    iso_27001:
      - control_a12_1_2  # Change management
