# Default values for contracts-service
replicaCount: 2

image:
  repository: registry.ssid.local/ssid/datasets-contracts
  pullPolicy: IfNotPresent
  tag: "2.0.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: datasets-contracts.ssid.example
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  LOG_LEVEL: INFO
