apiVersion: v1
kind: Service
metadata:
  name: documents-service
  namespace: ssid-data_layer
spec:
  selector:
    app: documents
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
