apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: education-hpa
  namespace: ssid-datasets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: education-service
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
