name: fee-distribution-ci
on:
  push:
    paths:
      - '03_core/**'
      - '07_governance_legal/**'
      - '08_identity_score/**'
      - '11_test_simulation/**'
      - '23_compliance/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -q 11_test_simulation
