name: ssid-ci-full (OPA + WASM + Playwright Full Suite)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  full_pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Root Integrity Check
        run: python 11_test_simulation/tools/root_integrity_validator.py --repo . --fail_on_violation

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Cache OPA
        id: cache-opa
        uses: actions/cache@v4
        with:
          path: ~/.opa
          key: opa-0.64.0

      - name: Download OPA
        if: steps.cache-opa.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.opa
          curl -L -o ~/.opa/opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x ~/.opa/opa

      - name: Add OPA to PATH
        run: echo "~/.opa" >> $GITHUB_PATH

      # ============================================================
      # OPA Policy Validation
      # ============================================================

      - name: Policy Check (pricing_enforcement.rego)
        run: |
          ~/.opa/opa eval \
            --format pretty \
            --data 23_compliance/policies/pricing_enforcement.rego \
            --input 07_governance_legal/docs/pricing/enterprise_subscription_model_v5.json \
            'data.ssid.pricing.allow'

      - name: Policy Check (rat_enforcement.rego)
        run: |
          cat <<'JSON' > /tmp/rat_input.json
          {
            "model": $(cat 07_governance_legal/docs/pricing/enterprise_subscription_model_v5.json),
            "request": { "tier": "global_proof_suite", "regions": ["DACH","EN-EU"], "bundles": ["global_bundle"] }
          }
          JSON
          ~/.opa/opa eval \
            --format pretty \
            --data 23_compliance/policies/rat_enforcement.rego \
            --input /tmp/rat_input.json \
            'data.ssid.rat.allow'

      # ============================================================
      # WASM Build & Verification
      # ============================================================

      - name: Build WASM from OPA Policies
        run: |
          mkdir -p build/wasm
          ~/.opa/opa build -t wasm \
            -e data.ssid.pricing.computed_price_eur \
            -o build/wasm/bundle.tar.gz \
            23_compliance/policies/

          # Extract WASM from bundle
          cd build/wasm
          tar -xzf bundle.tar.gz
          mv policy.wasm pricing_enforcement.wasm

      - name: Compute WASM SHA-256
        run: |
          cd build/wasm
          sha256sum pricing_enforcement.wasm | awk '{print $1}' > pricing_enforcement.sha256
          echo "WASM Hash: $(cat pricing_enforcement.sha256)"

      - name: Move WASM artifacts
        run: |
          mkdir -p dist/policies
          cp build/wasm/pricing_enforcement.wasm dist/policies/
          cp build/wasm/pricing_enforcement.sha256 dist/policies/

      # ============================================================
      # Playwright E2E Suite
      # ============================================================

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Static Preview
        run: |
          mkdir -p dist/07_governance_legal/docs/pricing
          mkdir -p dist/13_ui_layer/i18n/regions

          # Copy pricing model
          cp 07_governance_legal/docs/pricing/enterprise_subscription_model_v5.json \
             dist/07_governance_legal/docs/pricing/

          # Copy region registry
          cp 13_ui_layer/i18n/regions/region_activation_registry.json \
             dist/13_ui_layer/i18n/regions/

          # Start preview server
          npx http-server dist -p 8080 &
          echo $! > /tmp/http_pid
          sleep 3

      - name: Run Playwright E2E (Basic Suite)
        run: npx playwright test 13_ui_layer/e2e/pricing.spec.ts
        env:
          BASE_URL: http://127.0.0.1:8080

      - name: Run Playwright E2E (Extended Suite)
        run: npx playwright test 13_ui_layer/e2e/pricing_extended.spec.ts
        env:
          BASE_URL: http://127.0.0.1:8080

      - name: Run Playwright E2E (WASM Suite)
        run: npx playwright test 13_ui_layer/e2e/playwright_wasm.spec.ts
        env:
          BASE_URL: http://127.0.0.1:8080

      - name: Stop Preview
        if: always()
        run: |
          if [ -f /tmp/http_pid ]; then
            kill $(cat /tmp/http_pid) || true
          fi

      # ============================================================
      # Artifact Upload
      # ============================================================

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opa-wasm-bundle
          path: |
            dist/policies/pricing_enforcement.wasm
            dist/policies/pricing_enforcement.sha256

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # ============================================================
      # Performance & Coverage Summary
      # ============================================================

      - name: CI Performance Summary
        if: always()
        run: |
          echo "=== CI Full Pipeline Summary ==="
          echo "OPA Policies: VALIDATED"
          echo "WASM Build: COMPLETE"
          echo "E2E Tests: $(find playwright-report -name '*.json' | wc -l) suites"
          echo "WASM Hash: $(cat dist/policies/pricing_enforcement.sha256)"
