name: Pre-Commit Hooks Validation
version: "1.0.0"

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  pre-commit-validation:
    name: Pre-Commit Hooks Execution
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pyyaml

      - name: Verify pre-commit configuration
        run: |
          echo "=========================================="
          echo "Pre-Commit Configuration Verification"
          echo "=========================================="

          if [ -f ".pre-commit-config.yaml" ]; then
            echo "✅ .pre-commit-config.yaml found"
            echo ""
            echo "Configured hooks:"
            pre-commit run --all-files --show-diff-on-failure || {
              EXIT_CODE=$?
              echo ""
              echo "⚠️ Pre-commit hooks exited with code $EXIT_CODE"
              if [ $EXIT_CODE -eq 1 ]; then
                echo "Some hooks failed - review output above"
              fi
              exit $EXIT_CODE
            }
          else
            echo "❌ ERROR: .pre-commit-config.yaml not found"
            exit 1
          fi

      - name: Upload pre-commit artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pre-commit-validation-reports
          path: |
            .pre-commit-config.yaml
          retention-days: 30
