name: Quarterly Audit Report

on:
  schedule:
    - cron: '0 0 1 */3 *'  # First day of quarter
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate audit report
        run: |
          python3 scripts/audit/generate_quarterly_report.py
      
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: quarterly-audit-report
          path: reports/audit/quarterly-*.pdf
